server:
  port: 8081
spring:
  datasource:
    username: root
    password: ^abc123$
    url: jdbc:mysql://localhost:3306/ssm?characterEncoding=utf8&useSSL=false&serverTimezone=GMT-7&allowPublicKeyRetrieval=true&allowMultiQueries=true
mybatis:
  type-aliases-package: com.lisz.entity
  mapper-locations:
  - classpath:mybatis/mapper/*.xml
fdfs:
  connect-timeout: 600
  tracker-list:
  - 192.168.1.120:22122
  so-timeout: 1500
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  